### ISSUE TITLE
First selected item missing in models and indexes

### ISSUE THREAD

**Issue by vundyalaavinash** [thgreasi/ui-sortable-multiselection#16]
The first selected item or if a single item is dragged and dropped in connected list then its not reflected in the 
ui.item.sortableMultiSelect.indexes  or ui.item.sortableMultiSelect.models

**Comment by thgreasi** [comment]
That is by design.
The `ui.item.sortableMultiSelect.indexes ` only tracks the extra items that are added to the helper, since the dragged item will be handled by ui-sortable itself.

**Comment by thgreasi** [comment]
You can still access the dragged item's index from `ui.item.sortable.index`. I hope this does not overly-complicate your implementation.
