### ISSUE TITLE
Multiselection not working when disabling the debug info

### ISSUE THREAD

**Issue by IvanKraljevic** [thgreasi/ui-sortable-multiselection#17]
If you try to select multiple items when using [`$compileProvider.debugInfoEnabled(false)`](https://docs.angularjs.org/api/ng/provider/$compileProvider#debugInfoEnabled) you'll get an error:
```TypeError: Cannot read property 'sortableMultiSelect' of undefined```

This occurs because the directive tries to get the scope of the parent element. And because the debug info is disabled, the parent element's (or any other element's) scope is undefined.

Ui-sortable has the same problem in verisons prior to 0.13.3: [https://github.com/angular-ui/ui-sortable/issues/291](https://github.com/angular-ui/ui-sortable/issues/291)

**Comment by thgreasi** [comment]
Yes, that's true.
As you saw, I fixed it on UI-Sortable but never upgraded the implementation of this directive.
I will start working on it at some point.

**Comment by thgreasi** [comment]
@IvanKraljevic I just pushed the [v0.4.x-dev branch](https://github.com/thgreasi/ui-sortable-multiselection/tree/v0.4.x-dev) that hopefully adds support for the case that debugInfo is disabled.
Can you give it a try?
If it works we can probably publish it during the weekend.

**Comment by IvanKraljevic** [comment]
Hi, I just tested it and everything is working as it should.
Thanks for the quick response and fix.
Cheers! :)

**Comment by thgreasi** [comment]
Great! I will schedule the release during the weekend!

> --
*Thodoris Greasidis*
Computer, Networking &
Communications Engineer

**Comment by thgreasi** [comment]
Resolved with #18 and published as [v0.4.0](https://github.com/thgreasi/ui-sortable-multiselection/releases/tag/v0.4.0).
