### ISSUE TITLE
Event that fires when an item is selected

### ISSUE THREAD

**Issue by pedro-mass** [thgreasi/ui-sortable-multiselection#23]
Is there a way to know which items are selected without a drag?

**Comment by thgreasi** [comment]
We [trigger `ui-sortable-selectionschanged` on the `ui-sortable` element](https://github.com/thgreasi/ui-sortable-multiselection/blob/master/src/ui.sortable.multiselection.js#L59). I hope that it's exaclty what you are looking for. Feel free to re-open in any case.

**Comment by pedro-mass** [comment]
Yeah but how do we use it?

I checked the docs for ui-sortable, and didn't see any even matching that name.

**Comment by thgreasi** [comment]
Changed the [simple example found in README](http://codepen.io/thgreasi/pen/mJAcL) to demonstrate how the event can be used. Hope it helps.

**Comment by pedro-mass** [comment]
Thank you! I didn't realize you could listen to events on the element like that :)
