### ISSUE TITLE
Moving single item does not deselect item on drop

### ISSUE THREAD

**Issue by geofreyflores** [thgreasi/ui-sortable-multiselection#28]
To reproduce, I've used the Multiselect on Click demo: http://codepen.io/thgreasi/pen/KgoPmY

1. Select a single item; highlighted yellow
2. drag and drop to new position

Expected result: item is deselected (yellow highlight gone)
Actual result: item is still selected and highlighted

**Comment by thgreasi** [comment]
You are correct. I will release a new version in the weekend.

**Comment by thgreasi** [comment]
Resolved by #29

**Comment by thgreasi** [comment]
Published as v0.7.0. Thanks for your contribution on this :+1:
