### ISSUE TITLE
Respect jQuery UI Sortable 'cancel' option

### ISSUE THREAD

**Issue by jessefoster** [thgreasi/ui-sortable-multiselection#8]
jQuery UI allows you to specify a selector which prevent sorting on matching elements, [cancel dcoumentation.](http://api.jqueryui.com/sortable/#option-cancel)

I modified the code locally but can't do a pull request at work.  For now here's the changes I made in uiSortableSelectable directive.  I can submit a pull request later if you're fine with the modifications.
```javascript
function(selectedItemClass) {
      return {
        link: function(scope, element/*, attrs*/) {
          element.on('click', function (e) {
            var $this = angular.element(this);

            var $parent = $this.parent();
            var parentScope = $parent.scope();
            var jquerySortableCancelOption = $parent.sortable('option', 'cancel');

            // Respect jQuery UI Sortable's cancel option
            if ( jquerySortableCancelOption !== undefined && $this.is( jquerySortableCancelOption ) ) {
              return;
            }
....
```

**Comment by thgreasi** [comment]
That's great :+1: and with minimal diff!!!
I would be more than happy to merge such a PR.
